### ISSUE TITLE
Getting started page code conventions link broken

### ISSUE THREAD

**Issue by tjgilpin** [bradfrost/style-guide-guide#12]
Getting started page (http://bradfrost.github.io/style-guide-guide/getting-started.html) code conventions link broken

`... to learn more about <a href="/style-guide-guide/guidelines/code-conventions.html">code conventions</a>`
should be
`... to learn more about <a href="/style-guide-guide/guidelines/code.html">code conventions</a>`

**Comment by bradfrost** [comment]
@tjgilpin Thanks! I've gone through the whole site and added `baseurl` to all links to ensure links work locally and remotely.
