### ISSUE TITLE
Chevron SVG not loaded for guidelines and style overview in live github version

### ISSUE THREAD

**Issue by patrickhlauke** [bradfrost/style-guide-guide#16]
`<use href="..&#x2F;..&#x2F;icons.svg#chevron-right"></use>` in `_includes\patterns\01-molecules-02-blocks-card\01-molecules-02-blocks-card.markup-only.html` ends up resolving to `http://bradfrost.github.io/icons.svg` which obviously doesn't exist/404s

**Comment by bradfrost** [comment]
@patrickhlauke Thanks! I've added the `baseurl` `{{ "/icons.svg#chevron-right" | prepend: site.baseurl }}` so it works locally and remotely.
