### ISSUE TITLE
A11y feature request: strong focus style to help keyboard users navigate

### ISSUE THREAD

**Issue by elrat** [bradfrost/style-guide-guide#17]
While the default focus ring isn't ideal (and can get lost on some backgrounds) the subtly of the current focus style can be difficult for keyboard users to spot when tabbing through.

Judging by the comments on this article [ https://www.paciellogroup.com/blog/2012/04/how-to-remove-css-outlines-in-an-accessible-manner/ ] it seems to be a complicated business getting it right for keyboard and mouse users.

**Comment by bradfrost** [comment]
@elrat thanks for the suggestion! I've added an outline for the focus state to make it more obvious.
