### ISSUE TITLE
More thorough documentation

### ISSUE THREAD

**Issue by dlewand691** [bradfrost/style-guide-guide#23]
Tried the tool and was having some issues understanding how to make updates. Is there a plan to add more "how-to" documentation in the near future? 

If I'm understanding things correctly looking at the blocks-hero module, I have to update the rendered version as well as the markup-only files. This seems a bit difficult to maintain 2 versions. Another similar tool called Astrum has some very nice features and runs through the terminal. Check it out here:

[https://github.com/NoDivide/astrum](https://github.com/NoDivide/astrum)

Thanks and much appreciated!

**Comment by bradfrost** [comment]
@dlewand691 Thanks for the question and comment.

> Is there a plan to add more "how-to" documentation in the near future?

The Style Guide Guide is simply a Jekyll site, so their [documentation](https://jekyllrb.com/docs/home/) is the best place to look for updating the site.

As for importing/updating patterns, it's true that's a separate process. It doesn't require maintaining 2 versions, but that work happens elsewhere, such as in a tool like [Pattern Lab](http://patternlab.io). I wrote more about the setup in a post called [The Workshop and the Storefront](http://bradfrost.com/blog/post/the-workshop-and-the-storefront/), which explains the utility and relationship between the patt
where, such as in a tool like [Pattern Lab](http://patternlab.io). I wrote more about the setup in a post called [The Workshop and the Storefront](http://bradfrost.com/blog/post/the-workshop-and-the-storefront/), which explains the utility and relationship between the pattern-based design/dev environment, and the style guide.

It is possible to have your design/dev environment and style guide be one in the same, and it might make sense to do that depending on the situation. If that makes more sense, then go for it!
