### ISSUE TITLE
Syntax highlighting rendering

### ISSUE THREAD

**Issue by IonutParaschiv** [bradfrost/style-guide-guide#27]
Hi!

I'm trying to get syntax highlighting to work with rouge,  but for some reason the rendering is a bit off. The rendered classes for highlight seem really different than what rouge is documenting on their page (in this case, `class="token tag` instead of `class="ng` for example). I tried adding `highlighter: rouge` in config but that doesn't change anything. 
Is there a config somewhere that i'm missing?

**Comment by bradfrost** [comment]
@IonutParaschiv Style Guide Guide uses this Prism configuration for syntax highlighting: http://prismjs.com/download.html?themes=prism&languages=markup+css+clike+javascript+scss

You can find that file in `/js/vendor/prism.js` and replace it with something that better suits your needs.
