### ISSUE TITLE
Internacionalizaition

### ISSUE THREAD

**Issue by matbrgz** [bradfrost/style-guide-guide#34]
Is possible to add a i18n to this? How? I could help, but need details of implementation, like which "plugin" we will use, how text is rendered today, etc

**Comment by bradfrost** [comment]
@MatheusRV Style guide guide is merely a boilerplate scaffolding to get started with, so internationalizing the boilerplate text that's intentionally meant to get wiped out doesn't make too much sense. Feel free to elaborate if I'm misreading this, but I'm closing this out for now.
