### ISSUE TITLE
Button Get Started

### ISSUE THREAD

**Issue by brunopulis** [bradfrost/style-guide-guide#9]
In the url [http://bradfrost.github.io/style-guide-guide](http://bradfrost.github.io/style-guide-guide) the Get Started button points to a nonexistent or wrong path, returns error 404

**Comment by bradfrost** [comment]
Thanks @brunopulis. I've combed through the site and have fixed several links that were 404'ing. Thanks again!

**Comment by brunopulis** [comment]
We welcome @bradfrost :)
